### ISSUE TITLE
Renaming Suggestion of Method Names to Make Them More Descriptive

### ISSUE THREAD

**Issue by AnonymousAccount4SE** [DevelopLife/reviewtwits_backend#264]
# 🛠 Issue

### Renaming Suggestion of Method Names to Make Them More Descriptive
---
**Description**
---

We have developed a tool (**NameSpotter**) for identifying non-descriptive method names, and using this tool we find a non-descriptive method name in your repository:
```java
/* Non-descriptive Method Name in src/main/java/com/developlife/reviewtwits/service/email/EmailSender.java */
    private String creatUniqueKey() {
        String key;
        do {
            key = UUID.randomUUID().toString().substring(0, 8);
        } while(emailVerifyRepository.findByVerifyCode(key).isPresent());
        return key;
    }

```
We considered "creatUniqueKey" as non-descriptive because it contains typos "creat".

# 📝 Todo
We proposed renaming the method name to "createUniqueKey". 

Do you agree with the judgment? 

- If not, could you please leave your valuable opinion?

- If you do agree, the relevant modification has been submitted as a PR, and thanks for your precious time to consider it.

**Comment by WhalesBob** [comment]
Thank you for correcting our typos! Really appreciate it :)
